-- MySQL Script generated by MySQL Workbench
-- Sat Nov  4 23:41:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cadastro_aluno_stn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cadastro_aluno_stn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cadastro_aluno_stn` DEFAULT CHARACTER SET utf8 ;
USE `cadastro_aluno_stn` ;

-- -----------------------------------------------------
-- Table `cadastro_aluno_stn`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastro_aluno_stn`.`aluno` (
  `idaluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `cpf` VARCHAR(11) NULL,
  `email` VARCHAR(100) NULL,
  `telefone` VARCHAR(45) NULL,
  `dataNascimento` DATE NOT NULL,
  PRIMARY KEY (`idaluno`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadastro_aluno_stn`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastro_aluno_stn`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(100) NOT NULL,
  `numero` INT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  `complemento` VARCHAR(100) NULL,
  `aluno_idaluno` INT NOT NULL,
  PRIMARY KEY (`idendereco`),
  INDEX `fk_endereco_aluno1_idx` (`aluno_idaluno` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `cadastro_aluno_stn`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadastro_aluno_stn`.`responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastro_aluno_stn`.`responsavel` (
  `idresponsavel` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `aluno_idaluno` INT NOT NULL,
  PRIMARY KEY (`idresponsavel`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_responsavel_aluno1_idx` (`aluno_idaluno` ASC) VISIBLE,
  CONSTRAINT `fk_responsavel_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `cadastro_aluno_stn`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
